//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSB100_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryContent
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Author { get; set; }
        public System.DateTime Date { get; set; }
        public string Entry { get; set; }
        public bool Important { get; set; }
    
        public virtual UserCredentials UserCredentials { get; set; }
    }
}
